repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.12.1
    hooks:
      - id: mypy
        language_version: python3.12
        args: [ --strict, --check-untyped-defs ]

  - repo: https://github.com/pylint-dev/pylint
    rev: v3.3.1
    hooks:
      - id: pylint
        exclude: "docs"
        args: [ message_cipher, tests, ]
        stages: [ pre-push ]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.0
    hooks:
      - id: ruff
      - id: ruff-format

  - repo: local
    hooks:
      - id: unittests
        name: run unit tests
        pass_filenames: false
        entry: python3 -m unittest
        args: [ "discover", "--start-directory", "tests" ]
        language: system
        stages: [ pre-push ]
        types: [ python ]
