repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.6.1
    hooks:
    -   id: mypy
        language_version: python3.12
        args: [--strict]

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.1.3
  hooks:
    - id: ruff
