[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "message_cipher"
version = "1.1.0"
authors = [
  { name="Harry Parkes", email="harrydparkes@proton.me" },
]
description = "A simple cipher package"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/hazzery/MessageCipher"
"Bug Tracker" = "https://github.com/hazzery/MessageCipher/issues"
